[profile.default]
src = "src"
solc = "0.8.19"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@diamond-standard/=lib/Diamond-Foundry/src/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
goerli = "https://eth-goerli.g.alchemy.com/v2/zdTXkM4pBnyi95m5eQ_wJeTwXd7ry7R-"